### ISSUE TITLE
Wrong port number printed

### ISSUE THREAD

**Issue by gerardostola** [dannagle/PacketSender#106] opened 2018-02-21 22:40 UTC
On the  TCP server window, where traffic is dumped, the "From TCP" port  prints an erroneous value.
For first packet, the port value is correct, but then it prints the same port as "To Port"

**Comment by dannagle** [comment] 2018-02-22 15:37
Indeed, it does. Bug confirmed. Looks like it is related to persistent connections. Non-persistent mode seems OK.

**Comment by dannagle** [comment] 2018-05-15 01:54
Fixed in development branch.

**Closed** 2018-06-24 13:09 UTC
Labels: bug
