### ISSUE TITLE
[BUG] Cursor in HEX box moves when app loses focus

### ISSUE THREAD

**Issue by zethon** [dannagle/PacketSender#311] opened 2023-03-03 18:09 UTC
#### What OS?

- [ ] Windows
- [x] Mac
- [ ] Linux (Which distro?)
- [ ] iOS (phone or ipad?)
- [ ] Android (phone or tablet?)

#### Description of issue

Enter a non-zero value in the HEX field, say: `01 23 45 67 89` then move the cursor so that it is between `23` and `45`. Then switch to another application window, then come back to PacketSender. The cursor has moved to the end of input.

**Comment by dannagle** [comment] 2023-03-03 23:59
Thanks for submitting. I was able to recreate this in Windows. I don't know the root cause yet, so this ticket is remaining open. 

I do a lot of event triggering (such as on-text-changed) on those fields to keep the ASCII and HEX in sync with each other. For me, I had to type something in the other window and then alt-tab back. My cursor was now at the end. Perhaps that triggers an event somehow. Unfortunately, it may be triggering an event I need to keep.

**Comment by dannagle** [comment] 2024-10-12 00:48
I need my event triggers, so I am closing this as "won't fix", but there is a good alternative workflow.

Double-click the single line editor to bring up the multi-line editor. 

Screenshot:
![image](https://github.com/user-attachments/assets/6265ad73-3320-42f9-b963-92df3449f83a)

You can leave your cursor anywhere in that multi-line editor as you navigate away. When finished, click Update to update the main editor. I tested this on Windows with `my_cursor_here` and I was able to navigate anywhere and come back easy.

**Closed** 2024-10-12 00:48 UTC
Labels: wontfix
