### ISSUE TITLE
windows console does not wait given interval

### ISSUE THREAD

**Issue by lazna** [dannagle/PacketSender#45] opened 2016-07-09 18:34 UTC
Seems like console version does not wait for answer 5 seconds (-w 5000) and terminate immediatelly.  On GUI usage two devices respond, on console only one. Look like program terminate on first packet arrival. Or am I doing something wrong?

L.

-----------------------------------------
C:\utils\PacketSender>ptime packetsender -uw 5000 255.255.255.255 10001 "01 00 00 00"

ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

===  packetsender -uw 5000 255.255.255.255 10001 "01 00 00 00" ===
UDP (54916)://255.255.255.255:10001 01 00 00 00
Response Time:8:25:07.661 odp.
Response HEX:01 00 00 7C 02 00 0A DC 9F DB 40 2E 40 0A 0C 66 E3 02 00 0A DC 9F DB 40 2E 40 A9 FE 2E 40 01 00 06 DC 9F DB 40 2E 40 0A 00 04 0
0 10 66 6A 0B 00 11 35 4B 76 65 74 6E 61 31 38 2D 42 61 73 65 5F 4A 5A 0C 00 03 4E 42 35 0D 00 07 42 61 73 65 2D 4A 5A 0E 00 01 02 03 00 22
58 4D 2E 61 72 37 32 34 30 2E 76 35 2E 35 2E 36 2E 31 37 37 36 32 2E 31 33 30 35 32 38 2E 31 37 35 35 10 00 02 E2 B5
Response ASCII:\01\00\00|\02\00\n\dc\9f\db@.@\n\0cf\e3\02\00\n\dc\9f\db@.@\a9\fe.@\01\00\06\dc\9f\db@.@\n\00\04\00\10fj\0b\00\115Kvetna18-Ba
se_JZ\0c\00\03NB5\r\00\07Base-JZ\0e\00\01\02\03\00"XM.ar7240.v5.5.6.17762.130528.1755\10\00\02\e2\b5

Execution time: 0.056 s
-----------------------------------------------

**Comment by dannagle** [comment] 2016-07-09 20:26
That's by design on the console. It waits "up to X" until the first packet arrives. The GUI version is always listening for packets. 

The console version of Packet Sender is not as feature-rich as the GUI.

**Comment by lazna** [comment] 2016-07-10 05:58
Thanks for reply. It is very uncommon for such type of program, to terminate after first packet arrival. Please note it in help or change behaviour (prefered), this is very confusing :-/

**Comment by dannagle** [comment] 2016-07-22 18:47
Master branch now does this. You can grab it now if you are comfortable compiling or wait for installers.

**Comment by dannagle** [comment] 2016-07-23 20:38
Installers released. Closing this issue.

**Closed by dannagle** 2016-07-23 20:38 UTC
Labels: enhancement

**Comment by lazna** [comment] 2016-07-24 18:51
Thank you, this is MUCH better!

**Comment by dannagle** [comment] 2016-07-24 19:11
Happy you like it. Please share the app and donate if you find it useful.
