### ISSUE TITLE
Bug regarding Smart Response option

### ISSUE THREAD

**Issue by Aarti506** [dannagle/PacketSender#216] opened 2020-12-18 04:11 UTC
#### What OS?

- [ ] Linux (18.04)

#### Description of issue
Smart response is responding only once , even though i am sending a same data packet to the packet sender.
I am receiving the response only once.Later it is stopped responding.

**Comment by febalci** [comment] 2020-12-18 15:18
OSX 11 Big Sur and OSX Catalina; same problem.

**Comment by febalci** [comment] 2020-12-18 15:20
Duplicate of #108

**Comment by Aarti506** [comment] 2020-12-19 09:13
This issue is not found while working with UDP

**Comment by dannagle** [comment] 2021-03-16 01:10
Fixed in development branch.

**Closed by dannagle** 2021-03-16 01:10 UTC
